apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    route:
      receiver: telegram-notifications
      group_by: ['alertname', 'instance']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
    - name: telegram-notifications
      telegram_configs:
      - bot_token: "8075223350:AAExz8_l7LzzKAMTsXz-wYOSpRpLolAfIFQ"
        chat_id: -1002640710275  
        send_resolved: true  
        message: |
          {{ .CommonAnnotations.summary }}
          {{ .CommonAnnotations.description }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager
        args:
        - "--config.file=/etc/alertmanager/alertmanager.yml"
        - "--storage.path=/alertmanager"
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  selector:
    app: alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093