apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "nodeexporter"
        static_configs:
          - targets: ["node-exporter:9100"]

      - job_name: "postgres"
        static_configs:
          - targets: ["postgres-exporter:9187"]

    alerting:
      alertmanagers:
      - static_configs:
        - targets: ["alertmanager:9093"]  

    rule_files:
      - /etc/prometheus/alert_rules.yml

  alert_rules.yml: |
    groups:
    - name: InstanceDown
      rules:
        - alert: InstanceDown
          expr: up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Instance {{ $labels.instance }} down"
            description: "{{ $labels.instance }} has been down for more than 1 minute."

    - name: memory-alerts
      rules:
        - alert: HighMemoryUsage
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 30
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High RAM usage on {{ $labels.instance }}"
            description: "Used {{ printf \"%.2f\" $value }}% RAM (threshhold: 30%)."

    - name: cpu-alerts
      rules:
        - alert: HighCPUUsage
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 30
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage on {{ $labels.instance }}"
            description: "CPU usage is above 30% for the last 5 minutes on {{ $labels.instance }}"

    - name: cputemp-alerts
      rules:
        - alert: HighCPUTemperature
          expr: node_hwmon_temp_celsius > 30
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "High CPU temperature on {{ $labels.instance }}"
            description: "The CPU temperature is {{ printf \"%.2f\" $value }}°C, which exceeds the threshold of 30°C."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-storage
          mountPath: /prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090