route:
  receiver: telegram-notifications
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: telegram-notifications
  telegram_configs:
  - bot_token: "8075223350:AAExz8_l7LzzKAM********T"
    chat_id: -100*****  
    send_resolved: true  
    message: |
      {{ .CommonAnnotations.summary }}
      {{ .CommonAnnotations.description }}
