route:
  receiver: slack-notifications
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: slack-notifications
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#noub'             
    send_resolved: true
    title: '{{ .CommonAnnotations.summary }}'
    text: '{{ .CommonAnnotations.description }}'

