version: '3.8'

configs:
  nginx_conf:
    file: ./nginx/appseed-app.conf

services:
  db:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db_network
      - web_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.db == true 
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - db_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker 
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    depends_on:
      - db

  appseed-app:
    image: mikerockin1988/ecommerce-flask-stripe-appseed-app:1.0
    networks:
      - db_network
      - web_network
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/mydata?connect_timeout=10
    deploy:
      mode: replicated
      replicas: 2  
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/"]  
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "5085:5085"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/appseed-app.conf
    networks:
      - web_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
    depends_on:
      - appseed-app

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    networks:
      - web_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager 
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  node_exporter:
    image: prom/node-exporter
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - "9100:9100"
    networks:
      - web_network
    deploy:
      mode: global  
      resources:
        limits:
          cpus: "0.1"
          memory: 64M

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:1234@db:5432/mydata?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - db_network
      - web_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    depends_on:
      - db

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - web_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.3"
          memory: 256M

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    ports:
      - "9093:9093"
    networks:
      - web_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.2"
          memory: 128M

networks:
  db_network:
    driver: overlay
    attachable: true
  web_network:
    driver: overlay
    attachable: true

volumes:
  postgres-data:
  prometheus_data:
  grafana-storage:
