global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "nodeexporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]  


rule_files:
  - "alert_rules.yml"  