apiVersion: apps/v1
kind: Deployment
metadata:
  name: appseed-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appseed-app
  template:
    metadata:
      labels:
        app: appseed-app
    spec:
      containers:
      - name: appseed-app
        image: mikerockin1988/ecommerce-flask-stripe-appseed-app:1.0
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:1234@postgres:5432/mydata"
        ports:
        - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: appseed-app
spec:
  selector:
    app: appseed-app
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005